export const photos = [
  {
    album: "OFFICE",
    urls: [
      "building.jpg",
      "conference.jpg",
      "entry.jpg",
      "hall.jpg",
      "store.jpg",
      "cabin.jpg",
      "employee.jpg",
      "group.jpg",
      "office.jpg"
    ]
  },
  {
    album: "CES - 125 MW TPP -SENEGAL",
    urls: [
      "20161209_132520.jpg",
      "SENEGAL - 24.jpg",
      "20161209_132654.jpg",
      "SENEGAL - 11.jpg",
      "SENEGAL - 25.jpg",
      "20161209_150007.jpg",
      "SENEGAL - 12.jpg",
      "SENEGAL - 26.jpg",
      "20161209_150014.jpg",
      "SENEGAL - 27.jpg",
      "SENEGAL - 14.jpg",
      "SENEGAL - 28.jpg",
      "20161209_151719.jpg",
      "SENEGAL - 15.jpg",
      "SENEGAL - 2.jpg",
      "IMG-20170103-WA0007.jpg",
      "SENEGAL - 16.jpg",
      "SENEGAL - 3.jpg",
      "IMG-20170103-WA0008.jpg",
      "SENEGAL - 17.jpg",
      "SENEGAL - 4.jpg",
      "IMG-20170103-WA0009.jpg",
      "SENEGAL - 18.jpg",
      "SENEGAL - 5.jpg",
      "IMG-20170103-WA0013.jpg",
      "SENEGAL - 6.jpg",
      "IMG-20170103-WA0014.jpg",
      "SENEGAL - 7.jpg",
      "IMG-20170103-WA0018.jpg",
      "SENEGAL - 20.jpg",
      "SENEGAL - 8.jpg",
      "IMG-20170103-WA0022.jpg",
      "SENEGAL - 21.jpg",
      "SENEGAL - 9.jpg",
      "IMG-20170118-WA0024.jpg",
      "SENEGAL - 22.jpg",
      "MCC.jpg",
      "SENEGAL - 23.jpg",
    ],
  },
  {
    album: "DESAL - 100 MLD",
    urls: [
      "DESAL - 1.jpg",
      "DESAL - 4.jpg",
      "DESAL - 7.jpg",
      "DESAL - 2.jpg",
      "DESAL - 5.jpg",
      "DESAL - 8.jpg",
      "DESAL - 3.jpg",
      "DESAL - 6.jpg",
      "DESAL - 9.jpg",
    ],
  },
  {
    album: "FGUTPP - 1 x 500 MW",
    urls: [
      "FGUTPP - 10.jpg",
      "FGUTPP - 16.jpg",
      "FGUTPP - 21.jpg",
      "FGUTPP - 6.jpg",
      "FGUTPP - 11.jpg",
      "FGUTPP - 17.jpg",
      "FGUTPP - 22.jpg",
      "FGUTPP - 7.jpg",
      "FGUTPP - 12.jpg",
      "FGUTPP - 18.jpg",
      "FGUTPP - 2.jpg",
      "FGUTPP - 8.jpg",
      "FGUTPP - 13.jpg",
      "FGUTPP - 19.jpg",
      "FGUTPP - 3.jpg",
      "FGUTPP - 9.jpg",
      "FGUTPP - 14.jpg",
      "FGUTPP - 1.jpg",
      "FGUTPP - 4.jpg",
      "FGUTPP - 15.jpg",
      "FGUTPP - 20.jpg",
      "FGUTPP - 5.jpg",
    ],
  },
  {
    album: "PUJA",
    urls: [
      "20161007_170015.jpg",
      "20161007_170051.jpg",
      "20161007_170911.jpg",
      "20161007_170021.jpg",
      "20161007_170053.jpg",
    ],
  },
  {
    album: "RVUNL - 160 MW RAMGARH",
    urls: [
      "1.6.6KV SWITCHGEAR.jpg",
      "GTG BLDG. GTG TRANSFORMER.jpg",
      "1.BYPASS STACK.jpg",
      "GTGBuilding_Bypass Stack.jpg",
      "1.GTG.jpg",
      "HRSG ,GTG BLDG., BY PASS STACK,PIPE RACK.jpg",
      "1.GT OFF BASE EQUP..jpg",
      "HRSG_MAIN STACK.jpg",
      "1.HRSG.jpg",
      "over all.jpg",
      "1.UAT _ GTG.jpg",
      "RVUNL - 1.jpg",
      "220KVswitch Yard.jpg",
      "RVUNL - 2.jpg",
      "220KV Switch Yard.jpg",
      "RVUNL.jpg",
    ],
  },
  {
    album: "RVUNL - 330 MW DHOLPUR",
    urls: [
      "160 MVA GTPnl charged.jpg",
      "160MVA GT U.jpg",
      "160 MVA with Bus duct upto GCB.jpg",
      "220 KV SYD2.jpg",
      "ACW Pumps _ Piping works.jpg",
      "Aircompressorbuilding.jpg",
      "Boiler erection BHEL.jpg",
      "CCW Compressor house.jpg",
      "CCW PH  Compressor room.jpg",
      "Chimney BHEL.jpg",
      "Clarifier_PH pump erection.jpg",
      "Clarifier reactor tank_1.jpg",
      "Clarifier reactor tank_2.jpg",
      "Cooling Tower comp-2.jpg",
      "Cooling Tower.jpg",
      "Deggased water storage tank - Fab.jpg",
      "DM plant area_Pumps.jpg",
      "DM Plant Building with DM Tanks _ Equipments.jpg",
      "DM Plant - Erection of Tanks.jpg",
      "DM Plant.jpg",
      "DM Plant - Pumps erection.jpg",
      "DM Plant tanks.jpg",
      "DM Plant vessels.jpg",
      "DM Tank Erection.jpg",
      "Dm Tanks_painting.jpg",
      "Fire Fighting Line for UAT _ GT.jpg",
      "Frontal Piping.jpg",
      "FRP Cooling towers.jpg",
      "GCB with Busduct from GT to GCB.jpg",
      "GTG SWGR Charging Pooja.jpg",
      "Lighting works Swyd_CR.jpg",
      "LP Piping _ Cable trays.jpg",
      "LP Piping, Cable trays, Road _ Drainage.jpg",
      "PHE.jpg",
      "Pipe Rack FDN. BFP Build. Cooling Tower1.jpg",
      "Pipe racks with LP piping erct.jpg",
      "Pipe Rack with erect of pipes.jpg",
      "RWR_Comp_2.jpg",
      "RWR_PH with stop log gate.jpg",
      "STG B row col..jpg",
      "STG Building.jpg",
      "STG_ Building.jpg",
      "STG Control room, Deck _ turbine hall.jpg",
      "STG_CR Floor EL107.jpg",
      "STG_CR Floor EL.111.5M.jpg",
      "STG Deck CMD visit.jpg",
      "STG_Deck.jpg",
      "STG Machine Hall.jpg",
      "STG_MCR _ SYD_CR.jpg",
      "STG SWGR Room Panel charging1.jpg",
      "Switchyard with control room.jpg",
      "Swyd ACDB _ Batter Charger Pnl charged.jpg",
      "Swyd_CR Lighting works.jpg",
      "Swyd with control room.jpg",
      "SYD_Control room.jpg",
      "SYD_Eqpt. Erection.jpg",
      "SYD_Erection.jpg",
    ],
  },
]
